In [ ]:
import os
import numpy as np
import numpy as np
import argparse
import re
import sqlite3

import matplotlib
import matplotlib.pyplot as plt
from matplotlib.pyplot import MultipleLocator
from matplotlib import ticker

db_path = '/nfs/home/zhangchuanqi/lvna/for_xs/catlog/newdb50M-single-profiling/zeusmp/l3-5/hm.db'
con = sqlite3.connect(db_path)
cur = con.cursor()

In [ ]:
new_q = 'SELECT REQID,ISMISS,SITE,hm.STAMP,hm.tag,hp.wayidx,hm.ID FROM HitMissTrace hm LEFT JOIN HitPosTrace hp ON hm.STAMP=hp.STAMP WHERE hp.ISINS=0 ORDER BY hm.ID LIMIT 20;'

a_q = 'SELECT ISMISS,SITE,hm.STAMP,hp.wayidx,hm.ID,ISINS FROM HitMissTrace hm OUTER JOIN HitPosTrace hp ON hm.STAMP=hp.STAMP '\
    'where ismiss=1 ORDER BY hm.ID LIMIT 20;'

f = cur.execute(a_q)
out_res = [x for x in f]
print(out_res)

In [4]:
import numpy as np
a = np.arange(6)

b = np.repeat(a, 3)
print(b)
c = np.tile(a,3)
print(c)

na = a.reshape(3,2)

print(a.reshape(3,2).sum(axis=1))

print(na)
print(np.flip(na,axis=1))

[0 0 0 1 1 1 2 2 2 3 3 3 4 4 4 5 5 5]
[0 1 2 3 4 5 0 1 2 3 4 5 0 1 2 3 4 5]
[1 5 9]
[[0 1]
 [2 3]
 [4 5]]
[[1 0]
 [3 2]
 [5 4]]


In [5]:
grow_len = 32
for i in range(grow_len):
    print(f"{i/grow_len:.4%}")

0.0000%
6.2500%
12.5000%
18.7500%
25.0000%
31.2500%
37.5000%
43.7500%
50.0000%
56.2500%
62.5000%
68.7500%
75.0000%
81.2500%
87.5000%
93.7500%


In [10]:
import re
a = 'fullgrow6in32'
if a == 'atd' or re.search(r'fullgrow(\d+)in16',a):
    print('match')

In [4]:
full_t = list(range(1, 64+1))
for i in range(8):
    p = i
    x = full_t[p*8: (p+1)*8]
    print(i,x)

0 [1, 2, 3, 4, 5, 6, 7, 8]
1 [9, 10, 11, 12, 13, 14, 15, 16]
2 [17, 18, 19, 20, 21, 22, 23, 24]
3 [25, 26, 27, 28, 29, 30, 31, 32]
4 [33, 34, 35, 36, 37, 38, 39, 40]
5 [41, 42, 43, 44, 45, 46, 47, 48]
6 [49, 50, 51, 52, 53, 54, 55, 56]
7 [57, 58, 59, 60, 61, 62, 63, 64]
